name: run daily_notify.py #TODO:整合所有py檔至main.py

on:
  schedule:
    - cron: '25 23 * * *' #update at 0:00 UTC times everyday(Github在英國，所以這是台灣8:00am，但時間不準) #約在早上8:25會執行
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      FLASK_SECRET_KEY: ${{ secrets.FLASK_SECRET_KEY }}
      CHANNEL_ACCESS_TOKEN: ${{ secrets.CHANNEL_ACCESS_TOKEN }}
      CHANNEL_SECRET: ${{ secrets.CHANNEL_SECRET }}
      DATABASE_URL : ${{ secrets.DATABASE_URL }}

    steps:

      - name: checkout repo content
        uses: actions/checkout@v4 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.7' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # TODO    
      # - name: execute py script # run main.py
      #   run: python daily_crawler.py

      - name: notify
        run: python notification.py
      
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "daily crawl" --allow-empty)
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master 
